// fe/pages/auth/login.vue
<template>
  <div class="rounded-2xl p-10 max-w-[27rem] w-11/12 flex flex-col justify-center bg-white shadow-lg">
    <form @submit.prevent="onSubmit">
      <div class='flex flex-row gap-1 justify-center items-center'>
        <Icon name="ic:baseline-whatsapp" class='text-teal-600 text-[3rem]' />
        <h1 class='text-2xl uppercase'>Whats#<span class='text-teal-600'>App</span></h1>
      </div>
      <div class="text-center text-lg mt-5">Create or access your WhatsApp account to text your friends.</div>
      <div class="flex flex-col gap-1 mt-6">
        <label class="uppercase text-xs font-semibold">E-mail</label>
        <input
          type="email"
          class="text-lg border border-slate-300 rounded-2xl py-3 px-4 p font-medium bg-slate-50 focus:bg-white focus:outline-none"
          v-model="form.email"
          :class="errors.email ? 'focus:border-red-600' : 'focus:border-teal-600'"
        />
        <span v-show="errors.email" class="text-red-600 text-xs">
          {{ errors.email }}
        </span>
      </div>
      <div class="flex flex-col gap-1 mt-6">
        <label class="uppercase text-xs font-semibold">Password</label>
        <div class='relative'>
          <input
            :type="isPasswordVisible ? 'text' : 'password'"
            class="w-full text-lg border border-zinc-300 rounded-2xl py-3 pl-4 pr-10 p font-medium bg-zinc-50 focus:bg-white focus:outline-none"
            v-model="form.password"
            :class="errors.password ? 'focus:border-red-600' : 'focus:border-teal-600'"
          />
          <button type="button" class='absolute inset-y-0 right-0 text-slate-400 px-4 text-lg' @click="isPasswordVisible = !isPasswordVisible">
            <Icon v-if="isPasswordVisible" name="mdi:eye-outline" />  
            <Icon v-else name="mdi:eye-off-outline" />
          </button>
        </div>
        <span v-show="errors.password" class="text-red-600 text-xs">
          {{ errors.password }}
        </span>
        
        <button
          type="button"
          class="ml-auto font-semibold text-teal-700 hover:underline duration-300"
        >
          Forgot my password
        </button>
      </div>
      <button
        type="submit"
        class="mt-8 text-lg rounded-md bg-teal-600 w-full py-3 text-white font-semibold hover:bg-teal-700 duration-300"
      >
        Login
      </button>
      <button
        @click="$router.push('/auth/create-account')"
        type="button"
        class="mt-4 text-lg rounded-md border-2 border-teal-600 w-full py-3 text-teal-600 font-semibold hover:bg-teal-600 hover:text-white duration-300"
      >
        Create an account
      </button>
    </form>
  </div>
  </template>
  
<script>
import * as yup from 'yup'
import { mapActions } from 'pinia'
import { useUserStore } from '../../store/user'
import { useWsStore } from '../../store/websocket'

definePageMeta({
  layout: 'auth',
  middleware: 'auth'
})

export default {
  data() {
    return {
      isPasswordVisible: false,
      form: {
        email: '',
        password: ''
      },
      errors: {
        email: '',
        password: ''
      },
      isLoading: '' 
    }
  },
  computed: {
    schema() {
      return yup.object().shape({
        email: yup.string()
          .required()
          .email(),
        password: yup.string()
          .required()
      })
    }
  },
  watch: {
    form: {
      handler() {
        if (Object.keys(this.errors).some(key => !!this.errors[key])) {
          this.validate()
        }
      },
      deep: true
    }  
  },
  methods: {
    ...mapActions(useUserStore, ['setUser']),
    ...mapActions(useWsStore, ['connectWs']),
    clearError() {
      this.errors = {
        email: '',
        password: ''
      }
    },
    async validate() {
      this.clearError()
      try {
          await this.schema.validate(this.form, { abortEarly: false })
          return true
      } catch (err) {
          err.inner.forEach(error => {
            this.errors[error.path] = error.message
          })
          return false
      }
    },
    async onSubmit() {
      const isValid = await this.validate()
      if (!isValid) {
        return
      }
      const form = JSON.parse(JSON.stringify(this.form))
      const body = {
        email: form.email,
        password: form.password
      }
      this.isLoading = true
      try {
        const data = await useMyFetch('auth/login', { method: 'POST', body })
        if (!data.token) {
          throw new Error('Error')
        }
        this.setUser({
          _id: data._id,
          name: data.name,
          email: data.email,
          about: data.about,
          token: data.token
        })
        this.connectWs({ token: data.token })
        this.$router.push('/')
      } catch (error) {
        const data = error?.data || {}
        const message = Array.isArray(data.message) ? data.message[0] : data.message
        useNuxtApp().$toast.error(message)
      } finally {
        this.isLoading = false
      }
    }
  }
}
</script>

// frontend/src/app/auth/login/page.tsx
'use client'

import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { FaWhatsapp } from 'react-icons/fa'
import { LuEye, LuEyeOff } from 'react-icons/lu'

export default function Login() {
    const [isPasswordVisible, setIsPasswordVisible] = useState(false)
    const router = useRouter()

    return (
        <div className="h-full flex items-center justify-center mt-24">
            <div className="rounded-2xl p-10 max-w-[27rem] w-11/12 flex flex-col justify-center bg-white shadow-lg">
                <div className='flex flex-row gap-1 justify-center items-center'>
                    <span className='text-teal-600 text-[3rem]'>
                        <FaWhatsapp />
                    </span>
                    <h1 className='text-2xl uppercase'>Whats#<span className='text-teal-600'>App</span></h1>
                </div>
                <span className="text-center text-lg mt-5">Create or access your WhatsApp account to text your friends.</span>
                <div className="flex flex-col gap-1 mt-6">
                    <label className="uppercase text-xs font-semibold">E-mail</label>
                    <input type="email" className="text-lg border border-slate-300 rounded-2xl py-3 px-4 p font-medium bg-slate-50 focus:bg-white focus:border-teal-600 focus:outline-none" />
                </div>
                <div className="flex flex-col gap-1 mt-6">
                    <label className="uppercase text-xs font-semibold">Password</label>
                    <div className='relative'>
                        <input type={isPasswordVisible ? 'text' : 'password'} className="w-full text-lg border border-zinc-300 rounded-2xl py-3 pl-4 pr-10 p font-medium bg-zinc-50 focus:bg-white focus:border-teal-600 focus:outline-none"/>
                        <button className='absolute inset-y-0 right-0 text-slate-400 px-4 text-lg' onClick={() => setIsPasswordVisible(value => !value)}>
                            {
                                isPasswordVisible ? 
                                <LuEye /> :
                                <LuEyeOff />
                            } 
                        </button>
                    </div>
                    
                    <button className="ml-auto font-semibold text-teal-700 hover:underline duration-300">
                        Forgot my password
                    </button>
                </div>
                <button
                    className="mt-8 text-lg rounded-md bg-teal-600 w-full py-3 text-white font-semibold hover:bg-teal-700 duration-300"
                >
                    Login
                </button>
                <button
                    className="mt-4 text-lg rounded-md border-2 border-teal-600 w-full py-3 text-teal-600 font-semibold hover:bg-teal-600 hover:text-white duration-300"
                    onClick={() => router.push('/auth/create-account')}
                >
                    Create an account
                </button>
            </div>
        </div>  
    )
}
